.TH irman2lirc "1" "November 2001" "irman2lirc" FSF
.SH NAME
irman2lirc - converts irman.conf to lirc config file
.SH SYNOPSIS
.B irman2lirc
[\fIfile\fR]
.SH DESCRIPTION

If you already have a propper configuration file (irman.conf) for the libirman
package, irman2lirc will  convert it to lirc syntax with irman2lirc.
.TP
\fB\-\-help\fR
display usage summary
.SH "SEE ALSO"
The documentation for
.B lirc
is maintained as a html pages. They are located under html/ in the
documentadion directory.
